// api/chat.js - Vercel Serverless Function for MediMom Chatbot
import fetch from "node-fetch";

const SYSTEM_PROMPT = `You are Mia, MediMom's warm and knowledgeable pregnancy health assistant. You are like a trusted friend who also happens to be a medical expert.

Your personality:
- Warm, empathetic, and reassuring
- Never alarmist but always honest
- Use simple, clear language — avoid heavy medical jargon
- Use light, caring language like "I understand", "That's completely normal", "Let's look at this together"

Your capabilities:
- Answer pregnancy-related health questions
- Explain symptoms and when to be concerned
- Provide trimester-specific advice
- Give nutrition and lifestyle guidance
- Explain medical terms in simple language
- Check medication safety during pregnancy

Your boundaries:
- Only answer pregnancy, postpartum, and newborn-related questions
- For serious symptoms, always recommend consulting a doctor
- Never diagnose — only inform and guide
- If asked about non-pregnancy topics, gently redirect

When symptoms sound dangerous (severe headache + vision changes, heavy bleeding, no fetal movement, chest pain), always say: "This needs immediate medical attention. Please call your doctor or go to the nearest hospital now."

Keep responses concise — 2-4 short paragraphs max. Use line breaks for readability.`;

export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight request
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { messages } = req.body;

    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: 'Messages array is required' });
    }

    const API_KEY = process.env.GEMINI_API_KEY;

    if (!API_KEY) {
      return res.status(500).json({ error: 'API key not configured' });
    }

    // Convert messages to Gemini format
    // Gemini uses "user" and "model" roles (not "assistant")
    const geminiMessages = messages.map(msg => ({
      role: msg.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: msg.content }]
    }));

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          system_instruction: {
            parts: [{ text: SYSTEM_PROMPT }]
          },
          contents: geminiMessages,
          generationConfig: {
            maxOutputTokens: 1024,
            temperature: 0.7,
          }
        })
      }
    );

    const data = await response.json();

    if (data.error) {
      console.error("Gemini API Error:", data.error.message);
      return res.status(data.error.code || 400).json({ error: data.error.message });
    }

    if (!data.candidates || !data.candidates[0]?.content?.parts?.[0]?.text) {
      throw new Error("No content generated by Gemini");
    }

    const reply = data.candidates[0].content.parts[0].text;

    res.json({ reply });

  } catch (err) {
    console.error("SERVER ERROR:", err);
    res.status(500).json({ error: "Chat failed", message: err.message });
  }
}